### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by Juliankautsch** [MajronMan/Spicy-Sprockets#11]
Stwórz statyczną funkcję
public static GameObject CreatePopup(GameObject prefab);
wewnątrz nowej klasy InterfaceUtils, która tworzy (poprzez Instantiate)
popup, czyni dzieckiem UI (transform.SetParent) i przesuwa tak, aby róg
znajdował się tam, gdzie kursor, ale w taki sposób, żeby nie wychodzić
poza ekran (tj przy kliknięciu w lewym dolnym rogu ekranu, gdyby kursor
znajdował się w prawym górnym obiektu, ten wyszedłby poza ekran). Dodać
prefab popup’a do PrefabPaths i Prefabs.

**Comment by Juliankautsch** [comment]
12:00 piątek

**Comment by luknw** [comment]
Pierwsza wersja gotowa.
- po kliknięciu LPM na Map wyświetla się prymitywny popup
- popup przenosi się przy krawędzi
- po oddaleniu kamery i kliknięciu jeszcze raz na Mapie popup pojawia się w niezmienionej skali

#### Kolejny krok to:
wybór popupa w zależności od obiektu
#### Wymaga:
zrobić Collidery do obiektów, które wyglądają tak, jak się spodziewamy (-.-)
#### W przyszłości:
- popup jako automatyczne menu z przyciskami wczytywanymi z pliku
- ogarnięcie kamery i callbacki przy oddalaniu/przesuwaniu itd.
- ustandaryzowanie kolejności wyświetlania rzeczy (sorting layers)
- wybór obiektu za pomocą Raycastów(?)
